# Generated by Django 3.0.7 on 2020-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('Image', models.ImageField(default='neofetch.jpg', upload_to='')),
                ('genre', models.CharField(max_length=40)),
            ],
        ),
    ]
