# Generated by Django 3.0.7 on 2020-07-10 07:08

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='authorimage',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
