# Generated by Django 3.1 on 2020-09-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200710_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorName', models.CharField(max_length=20)),
                ('authorUsername', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authorImage', models.ImageField(default='profile.png', upload_to='')),
                ('authorBio', models.TextField(max_length=250)),
                ('authorTwitter', models.CharField(max_length=100)),
                ('authorInsta', models.CharField(max_length=100)),
                ('authorFacebook', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='authorimage',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('1', 'Anime'), ('2', 'Movies'), ('3', 'Series'), ('4', 'Novels'), ('5', 'Sports'), ('6', 'Poetry')], max_length=40),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyID', models.IntegerField(default=None)),
                ('Username', models.CharField(max_length=20)),
                ('commentContent', models.TextField(max_length=350)),
                ('commentlikes', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='authorUsername',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to='Blog.author'),
        ),
    ]
