# Generated by Django 3.1 on 2020-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subheading',
            field=models.CharField(default=" temporary fix for the storm at the night , I could take the losing sleep there's pill to help anxiety ", max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='authorFacebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorInsta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorTwitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movies', 'Movies'), ('Series', 'Series'), ('Novels', 'Novels'), ('Sports', 'Sports'), ('Poetry', 'Poetry')], max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mode',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=85, unique=True),
        ),
    ]
