# Generated by Django 3.0.7 on 2020-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorFacebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorInsta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorTwitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movies', 'Movies'), ('Series', 'Series'), ('Novels', 'Novels'), ('Sports', 'Sports'), ('Poetry', 'Poetry')], max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mode',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10),
        ),
    ]
